// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCfyNTkLTBlN-q-1mUwPzeYeDEAULOh2k',
    appId: '1:229111063824:web:9317772b06927716927195',
    messagingSenderId: '229111063824',
    projectId: 'shopping-list-559f4',
    authDomain: 'shopping-list-559f4.firebaseapp.com',
    storageBucket: 'shopping-list-559f4.firebasestorage.app',
    measurementId: 'G-3XQ1SQB8YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM5Eu97aoccIFcE_ZXRy8tg2nRP-kdpVk',
    appId: '1:229111063824:android:f864919630399826927195',
    messagingSenderId: '229111063824',
    projectId: 'shopping-list-559f4',
    storageBucket: 'shopping-list-559f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuoyjFEgCjbUjlq3T2X_Ecdhgh5gc0mfg',
    appId: '1:229111063824:ios:cddd49074f012bcd927195',
    messagingSenderId: '229111063824',
    projectId: 'shopping-list-559f4',
    storageBucket: 'shopping-list-559f4.firebasestorage.app',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuoyjFEgCjbUjlq3T2X_Ecdhgh5gc0mfg',
    appId: '1:229111063824:ios:cddd49074f012bcd927195',
    messagingSenderId: '229111063824',
    projectId: 'shopping-list-559f4',
    storageBucket: 'shopping-list-559f4.firebasestorage.app',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCfyNTkLTBlN-q-1mUwPzeYeDEAULOh2k',
    appId: '1:229111063824:web:86d36556bfe257c6927195',
    messagingSenderId: '229111063824',
    projectId: 'shopping-list-559f4',
    authDomain: 'shopping-list-559f4.firebaseapp.com',
    storageBucket: 'shopping-list-559f4.firebasestorage.app',
    measurementId: 'G-JPH2P03D40',
  );
}
