List<String> allProductslist = [
  "Avocado",
  "Coffee Beans",
  "Still Water",
  "Carrots",
  "Spinach(fresh)",
  "Jeans",
  "Sneakers",
  "Micellar Water",
  "Shapmo",
  "Aspririn",
  "Juice",
  "Bags",
  "Sunglasses",
  'Earrings',
  'Necklaces',
  'Bracelets',
  'Rings',
  'Anklets',
  'Toe Rings',
  'Nose Rings',
  'Cufflinks',
  'Brooches',
  'Pins',
  'Prescription Glasses',
  'Contact Lenses',
  'Blue-Light Glasses',
  'Hats',
  'Caps',
  'Beanies',
  'Berets',
  'Fedoras',
  'Visors',
  'Headbands',
  'Hijabs',
  'Turbans',
  'Hair Clips',
  'Hair Ties',
  'Shawls',
  'Silk Scarves',
  'Wool Scarves',
  'Bandanas',
  'Stoles',
  'Pashminas',
  'Gloves',
  'Mittens',
  'Fingerless Gloves',
  'Arm Warmers',
  'Tote Bags',
  'Clutches',
  'Crossbody Bags',
  'Shoulder Bags',
  'Backpacks',
  'Messenger Bags',
  'Leather Wallets',
  'Coin Purses',
  'RFID Wallets',
  'Money Clips',
  'Suitcases',
  'Passport Holders',
  'Travel Organizers',
  'Packing Cubes',
  'Duffel Bags',
  'Smartwatches',
  'Fitness Bands',
  'VR Headsets',
  'Bluetooth Glasses',
  'Mobile Phone',
  'Phone Cases',
  'PopSockets',
  'Wireless Chargers',
  'Screen Protectors',
  'Styluses',
  'Laptop',
  'Laptop Sleeves',
  'Keyboard Covers',
  'Styluses',
  'Stands',
  'Cooling Pads',
  'Headphones',
  'Earbuds',
  'Wireless'
      'Speakers',
  'Microphones',
  'Diamond Rings',
  'Gold Chains',
  'Designer Watches',
  'Gucci',
  'Louis Vuitton',
  'Chanel',
  'Prada Bags',
  'Designer Sunglasses',
  'Perfumes',
  'Personalized Jewelry',
  'Kimono Belts (Obi)',
  'Hair Sticks',
  'Jade Bracelets',
  'Beaded Necklaces',
  'Head Wraps',
  'Maasai Bracelets',
  'Bindis',
  'Bangles',
  'Jhumkas (Indian Earrings)',
  'Abaya Belts',
  'Kufi Caps',
  'Keffiyeh Scarves',
  'Leather Keychains',
  'Personalized Keychains',
  'LED Keychains',
  'Folding Umbrellas',
  'Transparent Umbrellas',
  'Fancy Pens',
  'Notebook Covers',
  'Bookmarks',
  'Car Air Fresheners',
  'Seat Covers',
  'Phone Holders',
  'Tents',
  'Sleeping Bags',
  'Flashlights',
  'Water Bottles Hydration Packs',
  'Desk Organizers & Stationery Holders',
  'Whiteboards & Corkboards',
  'Laptop Stands & Ergonomic Chairs',
  'Wall Clocks, Paintings, Picture Frames',
  'Vases & Indoor Plants',
  'Smart Plugs & Smart Bulbs',
  'Alexa',
  'Google Nest',
  'Smart Assistants',
  'Decorative Lights & LED Strips',
  'Seat Covers & Steering Wheel Covers',
  'Phone Mounts & Car Chargers',
  'Dash Cams & Parking Sensors',
  'Roof Racks & Cargo Boxes',
  'Bike Racks & Hitch Mounts',
  'Motorcycle Helmets',
  'Gloves',
  'Tank Bags',
  'Home Security Cameras & Sensors',
  "Beer",
  "Whiskey",
  "Wine",
  'Lager (Pale Lager, Pilsner, Dark Lager, Vienna Lager)',
  'Ale (Pale Ale, India Pale Ale (IPA), Brown Ale, Scotch Ale)',
  'Stout (Irish Stout, Oatmeal Stout, Imperial Stout)',
  'Porter (Baltic Porter, American Porter)',
  'Wheat Beer (Hefeweizen, Witbier, Berliner Weisse)',
  'Sour Beer (Gose, Lambic, Flanders Red Ale)',
  'Pilsner',
  'Bock (Doppelbock, Eisbock)',
  'Cabernet Sauvignon',
  'Merlot',
  'Pinot Noir',
  'Syrah/Shiraz',
  'Malbec',
  'Zinfandel',
  'Sangiovese',
  'Tempranillo',
  'Chardonnay',
  'Sauvignon Blanc',
  'Pinot Grigio',
  'Riesling',
  'Moscato',
  'Viognier',
  'Chenin Blanc',
  'Provence Rosé',
  'White Zinfandel',
  'Grenache Rosé',
  'Champagne'
  'Prosecco'
  'Cava'
  'Moscato d\'Asti',
  'Port',
  'Sherry',
  'Madeira',
  'Vermouth',
  'Scotch Whisky (Single Malt, Blended)',
  'Bourbon',
  'Rye Whiskey',
  'Irish Whiskey',
  'Japanese Whisky',
  'Canadian Whisky',
  'Tennessee Whiskey',
  'Cognac',
  'Armagnac',
  'Calvados',
  'Pisco',
  'Light Rum (White Rum)',
  'Dark Rum (Black Rum)',
  'Spiced Rum',
  'Overproof Rum',
  'Gin',
  'London Dry Gin',
  'Old Tom Gin',
  'Plymouth Gin',
  'Genever',
  'Vodka',
  'Plain Vodka',
  'Flavored Vodka',
  'Tequila & Mezcal',
  'Blanco (Silver)',
  'Reposado (Aged)',
  'Añejo (Extra Aged)',
  'Mezcal',
  'Martini',
  'Margarita',
  'Mojito',
  'Old Fashioned',
  'Manhattan',
  'Negroni',
  'Daiquiri',
  'Whiskey Sour',
  'Cosmopolitan',
  'Pina Colada',
  'Bloody Mary',
  'Moscow Mule',
  'Mai Tai',
  'Zombie',
  'Painkiller',
  'Blue Hawaiian',
  'Frozen Margarita',
  'Frozen Daiquiri',
  'Irish Coffee',
  'Hot Toddy',
  'Mulled Wine',
  "Diapers",
  "Baby Food",
  "Toys",
  'Baby Clothing',
  'Onesies (Bodysuits)',
  'Rompers',
  'Sleepsuits (Footed Pajamas)',
  'Baby Dresses',
  'Baby T-shirts & Tops',
  'Baby Pants & Leggings',
  'Baby Shorts',
  'Baby Socks & Booties',
  'Baby Hats & Beanies',
  'Baby Mittens',
  'Baby Jackets & Coats',
  'Baby Sweaters & Hoodies',
  'Baby Feeding Essentials ',
  ' Baby Bottles',
  'Bottle Nipples',
  'Sippy Cups',
  'Breast Pumps',
  'Formula Milk',
  'Baby Food & Purees',
  'Baby Food Makers',
  'High Chairs',
  'Bibs',
  'Burp Cloths',
  'Baby Utensils (Spoons, Forks)',
  'Baby Bowls & Plates',
  'Bottle Sterilizers',
  'Bottle Warmers',
  'Baby Diapering & Hygiene',
  'Disposable Diapers',
  'Cloth Diapers',
  'Diaper Rash Cream',
  'Baby Wipes',
  'Baby Powder',
  'Baby Lotion',
  'Baby Shampoo & Conditioner',
  'Baby Body Wash & Soap',
  'Baby Toothbrush & Toothpaste',
  ' Baby Nail Clippers',
  'Baby Hairbrush & Comb',
  'Changing Mats',
  'Baby Gear & Travel',
  'Strollers',
  'Car Seats',
  'Baby Carriers (Wraps, Slings)',
  'Baby Swings',
  'Baby Bouncers',
  'Baby Playpens',
  'Baby Walker',
  'Diaper Bags',
  'Pacifiers & Teethers',
  'Baby Monitors',
  'Baby Nursery & Bedding',
  'Cribs & Bassinets',
  'Crib Mattresses',
  'Baby Blankets',
  'Baby Pillows',
  'Sleep Sacks',
  'Mobiles & Nightlights',
  'Changing Tables',
  'Baby Toys & Entertainment',
  'Rattles & Teething Toys',
  'Plush Toys & Stuffed Animals',
  'Musical Toys',
  'Activity Gyms & Playmats',
  'Building Blocks',
  'Bath Toys',
  'Sensory Toys',
  "Coca-Cola",
  "Juice",
  "Mineral Water",
  'Water & Mineral Water',
  'Still Water',
  'Sparkling Water',
  'Flavored Water',
  'Alkaline Water',
  'Distilled Water',
  'Spring Water',
  'Electrolyte-Infused Water',
  'Soft Drinks & Carbonated Beverages',
  'Cola (Coke, Pepsi, etc.)',
  'Lemon-Lime Soda (Sprite, 7UP)',
  'Root Beer',
  'Ginger Ale',
  'Tonic Water',
  'Cream Soda',
  'Energy Drinks (Red Bull, Monster, etc.)',
  'Sports Drinks (Gatorade, Powerade, etc.)',
  'Juices & Fruit Drinks',
  'Orange Juice',
  'Apple Juice',
  'Grape Juice',
  'Pineapple Juice',
  'Cranberry Juice',
  'Pomegranate Juice',
  'Mango Juice',
  'Lemonade',
  'Limeade',
  'Watermelon Juice',
  'Mixed Berry Juice',
  'Carrot Juice',
  'Tomato Juice',
  'Dairy & Plant-Based Drinks',
  'Cow’s Milk (Whole, Skim, Low-Fat)',
  'Flavored Milk (Chocolate, Strawberry, etc.)',
  'Buttermilk',
  'Lassi',
  'Yogurt Drinks (Kefir, Ayran)',
  'Almond Milk',
  'Soy Milk',
  'Oat Milk',
  'Coconut Milk',
  'Cashew Milk',
  'Rice Milk',
  'Tea & Infusions',
  'Black Tea',
  'Green Tea',
  'White Tea',
  'Oolong Tea',
  'Herbal Tea (Chamomile, Peppermint, Hibiscus, etc.)',
  'Chai Tea',
  'Iced Tea',
  'Bubble Tea (Boba)',
  'Matcha Tea',
  'Coffee & Caffeinated Drinks',
  'Espresso',
  'Americano',
  'Cappuccino',
  'Latte',
  'Mocha',
  'Cold Brew Coffee',
  'Nitro Coffee',
  'Instant Coffee',
  'Decaffeinated Coffee',
  'Smoothies & Shakes',
  'Fruit Smoothies',
  'Green Smoothies',
  'Protein Shakes',
  'Milkshakes (Chocolate, Vanilla, Strawberry, etc.)',
  'raditional & Cultural Beverages',
  'Coconut Water',
  'Horchata (Rice & Cinnamon Drink)',
  'Falooda',
  'Aam Panna (Mango Drink)',
  'Sugarcane Juice',
  'Tamarind Juice',
  'Bael Juice',
  'Jallab (Middle Eastern Date Drink)',
  'Kvass (Fermented Rye Bread Drink)',
  "Bread",
  "Croissant",
  "Cake",
  'Breads',
  'White Bread',
  'Whole Wheat Bread',
  'Multigrain Bread',
  'Sourdough Bread',
  'Rye Bread',
  'Baguette',
  'Ciabatta',
  'Brioche',
  'Pita Bread',
  'Focaccia',
  'Flatbread',
  'Naan',
  'Cornbread',
  'Gluten-Free Bread',
  'Rolls & Buns',
  'Dinner Rolls',
  'Hamburger Buns',
  'Hot Dog Buns',
  'Kaiser Rolls',
  'Ciabatta Rolls',
  'Pretzel Rolls',
  'Brioche Buns',
  'Cakes & Pastries',
  'Birthday Cakes',
  'Cheesecake',
  'Red Velvet Cake',
  'Chocolate Cake',
  'Pound Cake',
  'Carrot Cake',
  'Fruitcake',
  'Swiss Roll',
  'Angel Food Cake',
  'Black Forest Cake',
  'Tiramisu',
  'Opera Cake',
  'Ice Cream Cake',
  'Cookies & Biscuits',
  'Chocolate Chip Cookies',
  'Oatmeal Raisin Cookies',
  'Peanut Butter Cookies',
  'Sugar Cookies',
  'Shortbread',
  'Macarons',
  'Gingerbread Cookies',
  'Fortune Cookies',
  'Muffins & Cupcakes',
  'Blueberry Muffins',
  'Chocolate Muffins',
  'Banana Muffins',
  'Corn Muffins',
  'Red Velvet Cupcakes',
  'Vanilla Cupcakes',
  'Chocolate Cupcakes',
  'Croissants & Danish Pastries',
  'Butter Croissant',
  'Chocolate Croissant',
  'Almond Croissant',
  'Cheese Danish',
  'Fruit Danish',
  'Cinnamon Rolls',
  'Pies & Tarts',
  'Apple Pie',
  'Pumpkin Pie',
  'Pecan Pie',
  'Cherry Pie',
  'Lemon Meringue Pie',
  'Key Lime Pie',
  'Custard Tart',
  'Fruit Tart',
  'Doughnuts & Fritters',
  'Glazed Doughnuts',
  'Chocolate Doughnuts',
  'Jelly-Filled Doughnuts',
  'Cream-Filled Doughnuts',
  'Apple Fritters',
  'Churros',
  'Savory Baked Goods',
  'Garlic Bread',
  'Pretzels',
  'Bagels',
  'Empanadas',
  'Samosas',
  'Quiche',
  'Puff Pastry Snacks',
  "Tuna",
  "Corn",
  "Beans",
  'Canned Vegetables',
  'Canned Corn',
  'Canned Peas',
  'Canned Green Beans',
  'Canned Carrots',
  'Canned Mushrooms',
  'Canned Spinach',
  'Canned Asparagus',
  'Canned Tomatoes',
  'Canned Beets',
  'Canned Potatoes',
  'Canned Mixed Vegetables',
  'Canned Fruits',
  'Canned Peaches',
  'Canned Pineapple',
  'Canned Pears',
  'Canned Mandarin Oranges',
  'Canned Applesauce',
  'Canned Cherries',
  'Canned Mango',
  'Canned Apricots',
  'Canned Lychee',
  'Canned Fruit Cocktail',
  'Canned Beans & Legumes',
  'Canned Black Beans',
  'Canned Kidney Beans',
  'Canned Chickpeas (Garbanzo Beans)',
  'Canned Pinto Beans',
  'Canned White Beans (Cannellini)',
  'Canned Lentils',
  'Canned Refried Beans',
  'Canned Baked Beans',
  'Canned Meat & Seafood',
  'Canned Tuna',
  'Canned Salmon',
  'Canned Sardines',
  'Canned Anchovies',
  'Canned Crab Meat',
  'Canned Chicken',
  'Canned Turkey',
  'Canned Corned Beef',
  'Canned Ham',
  'Canned Spam',
  'Canned Soups & Broths',
  'Canned Tomato Soup',
  'Canned Chicken Noodle Soup',
  'Canned Vegetable Soup',
  'Canned Clam Chowder',
  'Canned Minestrone',
  'Canned Beef Stew',
  'Canned Chili',
  'Canned French Onion Soup',
  'Canned Mushroom Soup',
  'Canned Lentil Soup',
  'Canned Chicken Broth',
  'Canned Beef Broth',
  'Canned Vegetable Broth',
  'Canned Pasta & Meals',
  'Canned SpaghettiOs',
  'Canned Ravioli',
  'Canned Mac & Cheese',
  'Canned Lasagna',
  'Canned Chili Mac',
  'Canned Beefaroni',
  'Canned Sauces & Condiments',
  'Canned Tomato Sauce',
  'Canned Pasta Sauce',
  'Canned Salsa',
  'Canned Enchilada Sauce',
  'Canned Coconut Milk',
  'Canned Alfredo Sauce',
  'Canned Pesto',
  'Canned Dairy & Desserts',
  'Canned Condensed Milk',
  'Canned Evaporated Milk',
  'Canned Whipped Cream',
  'Canned Rice Pudding',
  'Canned Custard',
  'Canned Chocolate Syrup',
  "Detergent",
  "Bleach",
  "Soap",
  "Multi-Surface Cleaner",
  "Disinfectant Spray",
  "Antibacterial Cleaner",
  "Eco-Friendly All-Purpose Cleaner",
  'Kitchen Cleaners',
  'Dishwashing Liquid (Dish Soap)',
  'Dishwasher Detergent (Pods, Powder, or Liquid)',
  'Oven Cleaner',
  'Stainless Steel Cleaner',
  'Glass Stove Top Cleaner',
  'Garbage Disposal Cleaner',
  'Countertop Cleaner',
  'Degreaser',
  'Bathroom Cleaners',
  'Toilet Bowl Cleaner',
  'Bathroom Tile Cleaner',
  'Mold & Mildew Remover',
  'Shower Glass Cleaner',
  'Drain Cleaner (Unclogging Gel)',
  'Floor Cleaners',
  'Hardwood Floor Cleaner',
  'Tile Floor Cleaner',
  'Carpet Shampoo',
  'Laminate Floor Cleaner',
  'Mop Solution',
  'Window & Glass Cleaners',
  'Glass Cleaner Spray',
  'Streak-Free Window Cleaner',
  'Ammonia-Based Glass Cleaner',
  'Laundry Cleaners'
      'Laundry Detergent (Liquid, Powder, or Pods)',
  'Fabric Softener',
  'Stain Remover (Spray, Stick, or Powder)',
  'Bleach (Regular & Color-Safe)',
  'Dryer Sheets',
  'Scent Boosters',
  'Disinfectants & Sanitizers',
  'Alcohol-Based Disinfectant Spray',
  'Sanitizing Wipes (Clorox/Lysol Wipes)',
  'Hand Sanitizer',
  'Hydrogen Peroxide',
  'Furniture & Upholstery Cleaners',
  'Wood Polish',
  'Leather Cleaner',
  'Fabric Upholstery Cleaner',
  'Air & Odor Cleaners',
  'Air Freshener Spray',
  'Odor Eliminator (Fabric & Carpet)',
  'Plug-In Air Fresheners',
  'Essential Oil Diffusers',
  'Specialty Cleaners',
  'Electronics & Screen Cleaner',
  'Car Interior Cleaner',
  'Jewelry Cleaner',
  'Shoe Cleaner',
  'Grout Cleaner',
  'Pet Stain & Odor Remover',
  "T-Shirt",
  "Jeans",
  "Sneakers",
  'T-Shirts',
  'Polo Shirts',
  'Dress Shirts',
  'Sweaters',
  'Hoodies & Sweatshirts',
  'Jackets & Coats',
  'Suits & Blazers',
  'Jeans',
  'Trousers',
  'Shorts',
  'Activewear',
  'Underwear',
  'Socks',
  'Sleepwear',
  'Swimwear',
  'Women\'s Clothing',
  'T-Shirts & Tops',
  'Blouses & Shirts',
  'Dresses',
  'Skirts',
  'Jeans',
  'Leggings & Tights',
  'Trousers & Pants',
  'Jumpsuits & Rompers',
  'Sweaters',
  'Hoodies & Sweatshirts',
  'Jackets & Coats',
  'Suits & Blazers',
  'Activewear',
  'Underwear & Bras',
  'Socks & Stockings',
  'Sleepwear & Loungewear',
  'Swimwear',
  'Kids Clothing',
  'Onesies & Bodysuits',
  'T-Shirts & Tops',
  'Dresses',
  'Jeans & Pants',
  'Shorts',
  'Hoodies & Sweaters',
  'Jackets & Coats',
  'Pajamas',
  'Socks & Tights',
  'School Uniforms',
  'Swimwear',
  'Shoes & Footwear',
  'Men’s Shoes',
  'Sneakers',
  'Formal Shoes',
  'Loafers',
  'Boots',
  'Sandals & Slippers',
  'Running Shoes',
  'Women’s Shoes',
  'Sneakers',
  'Heels & Pumps',
  'Flats',
  'Sandals',
  'Boots',
  'Wedges',
  'Running Shoes',
  'Kids’ Shoes',
  'Sneakers',
  'Sandals',
  'Boots',
  'School Shoes',
  'Slippers',
  'Accessories & Essentials',
  'Hats & Caps',
  'Gloves',
  'Belts',
  'Ties & Bowties',
  'Scarves',
  'Handbags & Purses',
  'Backpacks',
  'Sunglasses',
  'Watches',
  'Jewelry',
  "Coffee Beans",
  "Green Tea",
  "Hot Chocolate",
  'Coffee',
  'Whole Bean Coffee',
  'Ground Coffee',
  'Instant Coffee',
  'Decaffeinated Coffee',
  'Espresso Coffee',
  'Cold Brew Coffee',
  'Flavored Coffee (Vanilla, Caramel, Hazelnut, Mocha, etc.)',
  'Dark Roast',
  'Medium Roast',
  'Light Roast',
  'Single-Origin Coffee',
  'Blended Coffee',
  'Organic Coffee',
  'Fair Trade Coffee',
  'Coffee Pods & Capsules (Nespresso, Keurig, etc.)',
  'Tea',
  'Tea Powder',
  'Black Tea',
  'English Breakfast',
  'Earl Grey',
  'Assam Tea',
  'Darjeeling Tea',
  'Ceylon Tea',
  'Chai Tea',
  'Green Tea',
  'Matcha',
  'Sencha',
  'Jasmine Green Tea',
  'Genmaicha',
  'Gunpowder Green Tea',
  'Herbal Tea (Caffeine-Free)',
  'Chamomile',
  'Peppermint',
  'Hibiscus',
  'Rooibos',
  'Lemon Ginger',
  'Lavender Tea',
  'White Tea',
  'Silver Needle',
  'White Peony',
  'Oolong Tea',
  'Tieguanyin',
  'Wuyi Rock Tea',
  'Flavored & Specialty Teas',
  'Fruity Tea (Berry, Peach, Mango, etc.)',
  'Detox & Wellness Tea',
  'Bubble Tea Kits',
  'Tea Bags & Loose Leaf Tea',
  'Traditional Tea Bags',
  'Pyramid Tea Bags',
  'Loose Leaf Tea',
  'Cocoa & Hot Chocolate',
  'Hot Cocoa Mix',
  'Dark Chocolate Cocoa',
  'White Chocolate Cocoa',
  'Drinking Chocolate',
  'Organic Cocoa Powder',
  'Sugar-Free Cocoa Mix',
  'Flavored Cocoa (Peppermint, Caramel, etc.)',
  'Instant Cocoa Packets',
  'Coffee & Tea Accessories',
  'Coffee Beans Grinder',
  'Coffee Maker (Drip, Espresso, French Press, etc.)',
  'Coffee Filters',
  'Milk Frother',
  'Reusable Coffee Pods',
  'Teapots & Kettles',
  'Tea Infusers & Strainers',
  'Matcha Whisk',
  'Travel Mugs & Thermoses',
  "Milk",
  "Cheese",
  "Butter",
  'Whole Milk',
  '2% Reduced-Fat Milk',
  '1% Low-Fat Milk',
  'Skim (Fat-Free) Milk',
  'Organic Milk',
  'Lactose-Free Milk',
  'A2 Milk',
  'Goat Milk',
  'Sheep Milk',
  'Flavored Milk (Chocolate, Strawberry, Vanilla)',
  'Buttermilk',
  'Condensed Milk',
  'Evaporated Milk',
  'Powdered (Dry) Milk',
  'UHT (Ultra-High Temperature) Milk',
  'Cheese',
  'Hard Cheeses',
  'Cheddar (Mild, Sharp, Extra Sharp)',
  'Parmesan',
  'Asiago',
  'Romano',
  'Manchego',
  'Semi-Hard & Semi-Soft Cheeses',
  'Gouda',
  'Swiss',
  'Provolone Monterey Jack',
  'Colby',
  'Havarti',
  'Edam',
  'Soft Cheeses',
  'Brie',
  'Camembert',
  'Ricotta',
  'Mascarpone',
  'Cream Cheese',
  'Fresh Cheeses',
  'Mozzarella',
  'Feta',
  'Halloumi',
  'Paneer',
  'Burrata',
  'Cottage Cheese',
  'Blue Cheeses',
  'Gorgonzola',
  'Roquefort',
  'Stilton',
  'Processed & Specialty Cheeses',
  'American Cheese',
  'Cheese Slices',
  'Cheese Spread',
  'Butter & Margarine',
  'Salted Butter',
  'Unsalted Butter',
  'Clarified Butter (Ghee)',
  'Whipped Butter',
  'European-Style Butter',
  'Vegan Butter',
  'Margarine',
  'Spreadable Butter',
  'Yogurt & Dairy Alternatives',
  'Greek Yogurt',
  'Regular Yogurt',
  'Flavored Yogurt (Strawberry, Vanilla, etc.)',
  'Low-Fat Yogurt',
  'Non-Fat Yogurt',
  'Drinkable Yogurt',
  'Probiotic Yogurt',
  'Skyr (Icelandic Yogurt)',
  'Kefir',
  'Vegan Yogurt (Almond, Soy, Coconut, Cashew, Oat)',
  'Cream & Dairy-Based Products',
  'Heavy Cream',
  'Whipping Cream',
  'Half-and-Half',
  'Sour Cream',
  'Clotted Cream',
  'Crème Fraîche',
  'Ice Cream & Frozen Dairy',
  'Regular Ice Cream',
  'Low-Fat Ice Cream',
  'Gelato',
  'Sorbet (Dairy-Free)',
  'Frozen Yogurt',
  'Dairy-Free Ice Cream (Coconut, Almond, Oat, Cashew)',
  "Rice",
  "Pasta",
  "Lentils",
  'Rice & Grains',
  'White Rice (Long Grain, Short Grain, Basmati, Jasmine)',
  'Brown Rice',
  'Wild Rice',
  'Arborio Rice (for Risotto)',
  'Black Rice',
  'Red Rice',
  'Quinoa (White, Red, Black)',
  'Bulgur Wheat',
  'Barley',
  'Farro',
  'Couscous',
  'Millet',
  'Pasta & Noodles',
  'Spaghetti',
  'Penne',
  'Fusilli',
  'Macaroni',
  'Fettuccine',
  'Linguine',
  'Rigatoni',
  'Lasagna Sheets',
  'Angel Hair Pasta',
  'Orzo',
  'Whole Wheat Pasta',
  'Gluten-Free Pasta',
  'Ramen Noodles',
  'Udon Noodles',
  'Rice Noodles',
  'Soba Noodles',
  'Egg Noodles',
  'Beans, Lentils & Legumes',
  'Black Beans',
  'Kidney Beans',
  'Pinto Beans',
  'Chickpeas (Garbanzo Beans)',
  ' White Beans (Cannellini, Great Northern, Navy)',
  'Adzuki Beans',
  'Lentils (Green, Red, Brown, Yellow, Black)',
  'Split Peas (Green, Yellow)',
  'Mung Beans',
  'Soybeans',
  'Flour & Baking Essentials',
  'All-Purpose Flour',
  'Whole Wheat Flour',
  'Bread Flour',
  'Cake Flour',
  'Pastry Flour',
  'Self-Rising Flour',
  'Almond Flour',
  'Coconut Flour',
  'Cornmeal',
  'Semolina',
  'Tapioca Flour',
  'Arrowroot Flour',
  'Gluten-Free Flour Blends',
  'Sugar & Sweeteners',
  'White Sugar',
  'Brown Sugar',
  'Powdered Sugar',
  'Cane Sugar',
  'Coconut Sugar',
  'Honey',
  'Maple Syrup',
  'Agave Syrup',
  'Molasses',
  ' Artificial Sweeteners (Stevia, Aspartame, Sucralose, Monk Fruit)',
  'Breakfast Cereals & Oats',
  'Rolled Oats',
  'Quick Oats',
  'Steel-Cut Oats',
  'Instant Oatmeal',
  'Granola',
  'Muesli',
  'Corn Flakes',
  'Bran Flakes',
  'Puffed Rice Cereal',
  'Whole Grain Cereal',
  'Fruit & Nut Cereal',
  'Nuts & Seeds',
  'Almonds',
  'Walnuts',
  'Cashews',
  'Pistachios',
  'Pecans',
  'Hazelnuts',
  'Macadamia Nuts',
  'Peanuts',
  'Sunflower Seeds',
  'Pumpkin Seeds',
  'Flaxseeds',
  'Chia Seeds',
  'Sesame Seeds',
  'Hemp Seeds',
  'Dried Fruits',
  'Raisins',
  'Dried Cranberries',
  'Dried Apricots',
  'Dates',
  'Dried Figs',
  'Prunes',
  'Dried Apples',
  'Dried Mango',
  'Dried Pineapple',
  'Dried Blueberries',
  'Dried Bananas',
  'Miscellaneous Dry Goods',
  'Breadcrumbs (Panko, Regular)',
  'Cornstarch',
  'Baking Powder',
  'Baking Soda',
  'Yeast (Dry, Fresh)',
  'Gelatin',
  'Cocoa Powder',
  'Instant Coffee',
  'Tea Bags',
  'Hot Chocolate Mix',
  "Jasmin",
  "Rose",
  "Cornflower",
  'Rose',
  'Tulip',
  'Lily',
  'Sunflower',
  'Daisy',
  'Orchid',
  'Carnation',
  'Peony',
  'Hydrangea',
  'Chrysanthemum',
  'Daffodil',
  'Lavender',
  'Jasmine',
  'Poppy',
  'Marigold',
  'Lotus',
  'Protea',
  'Bird of Paradise',
  'Calla Lily',
  'Hibiscus',
  'Bluebell',
  'Bleeding Heart',
  'Amaryllis',
  'Camellia',
  'Wisteria',
  'Gardenia',
  'Nasturtium',
  'Chamomile',
  'Calendula',
  'Violets',
  'Borage',
  'Honeysuckle',
  'Dandelion',
  'Lavender (culinary use)',
  'Rose Petals',
  'Pansy',
  'Echinacea (Coneflower)',
  'Arnica',
  'Elderflower',
  'Passionflower',
  'St. John’s Wort',
  'Valerian',
  'Yarrow',
  'Red Clover',
  'Jasmine',
  'Gardenia',
  'Lavender',
  'Rose',
  'Lilac',
  'Honeysuckle',
  'Tuberose',
  'Sweet Pea',
  'Frangipani',
  'Hyacinth',
  'Daffodil',
  'Cherry Blossom',
  'Tulip',
  'Hyacinth',
  'Sunflower',
  'Daisy',
  'Marigold',
  'Zinnia',
  'Chrysanthemum',
  'Aster',
  'Dahlia',
  'Goldenrod',
  'Poinsettia',
  'Camellia',
  'Winter Jasmine',
  'Snowdrop',
  "Frozen Meat",
  "Ice cream",
  "Ice cubes",
  'rozen Peas',
  'Frozen Carrots',
  'Frozen Broccoli',
  'Frozen Cauliflower',
  'Frozen Spinach',
  'Frozen Green Beans',
  'Frozen Corn',
  'Frozen Mixed Vegetables',
  'Frozen Blueberries',
  'Frozen Strawberries',
  'Frozen Raspberries',
  'Frozen Mango',
  'Frozen Pineapple',
  'Frozen Avocado',
  'Frozen Cherries',
  'Frozen Pizza',
  'Frozen Pasta Meals',
  'Frozen Mac & Cheese',
  'Frozen Lasagna',
  'Frozen Stir-Fry Meals',
  'Frozen Burritos',
  'Frozen Enchiladas',
  'Frozen Rice Bowls',
  'Frozen Noodles',
  'Frozen Dumplings',
  'Frozen Sushi Rolls',
  'Frozen Curry Dishes',
  'Frozen Chicken Wings',
  'Frozen Chicken Breast',
  'Frozen Chicken Nuggets',
  'Frozen Meatballs',
  'Frozen Beef Patties',
  'Frozen Sausages',
  'Frozen Hot Dogs',
  'Frozen Bacon',
  'Frozen Shrimp',
  'Frozen Salmon',
  'Frozen Fish Fillets',
  'Frozen Crab Meat',
  'Frozen Lobster',
  'Frozen Scallops',
  'Ice Cream',
  'Frozen Yogurt',
  'Sorbet',
  'Gelato',
  'Frozen Cheesecake',
  'Frozen Brownies',
  'Frozen Cupcakes',
  'Frozen Cookie Dough',
  'Frozen Chocolate Bars',
  'Frozen Waffles',
  'Frozen Pancakes',
  'Frozen Bagels',
  'Frozen Croissants',
  'Frozen Biscuits',
  'Frozen Dinner Rolls',
  'Frozen Muffins',
  'Frozen Pie Crusts',
  'Frozen French Fries',
  'Frozen Mozzarella Sticks',
  'Frozen Onion Rings',
  'Frozen Chicken Tenders',
  'Frozen Spring Rolls',
  'Frozen Mini Pizzas',
  'Frozen Samosas',
  "Apple",
  "Orange",
  'Bananas',
  'Grapes',
  'Pears',
  'Peaches',
  'Plums',
  'Cherries',
  'Strawberries',
  'Blueberries',
  'Raspberries',
  'Blackberries',
  'Lemons',
  'Limes',
  'Tangerines',
  'Clementines',
  'Grapefruits',
  'Pomelos',
  'Mangoes',
  'Pineapples',
  'Papayas',
  'Guavas',
  'Kiwifruit',
  'Passionfruit',
  'Lychee',
  'Rambutan',
  'Dragon Fruit',
  'Starfruit',
  'Coconuts',
  'Jackfruit',
  'Durian',
  'Watermelon',
  'Cantaloupe',
  'Honeydew',
  'Galia Melon',
  'Peaches',
  'Nectarines',
  'Apricots',
  'Plums',
  'Cherries',
  'Dates',
  'Apples',
  'Pears',
  'Quinces',
  'Figs',
  'Persimmons',
  'Mulberries',
  'Tamarillo',
  'Sapodilla',
  'Longan',
  'Loquat',
  'Raisins',
  'Dates',
  'Prunes',
  'Dried Apricots',
  'Dried Figs',
  'Dried Cranberries',
  'Dried Mango',
  'Dried Pineapple',
  'Spinach',
  'Kale',
  'Lettuce (Romaine, Iceberg, Butterhead)',
  'Cabbage (Green, Red, Napa)',
  'Swiss Chard',
  'Collard Greens',
  'Arugula',
  'Mustard Greens',
  'Watercress',
  'Carrots',
  'Potatoes (Russet, Sweet, Red, Fingerling)',
  'Beets',
  'Turnips',
  'Radishes',
  'Parsnips',
  'Rutabaga',
  'Yams',
  'Daikon',
  'Broccoli',
  'Cauliflower',
  'Brussels Sprouts',
  'Bok Choy',
  'Kohlrabi',
  'Onions (Red, Yellow, White, Green)',
  'Garlic',
  'Shallots',
  'Leeks',
  'Chives',
  'Green Beans',
  'Peas (Snow Peas, Snap Peas, Green Peas)',
  'Lentils',
  'Chickpeas',
  'Soybeans',
  'Black Beans',
  'Kidney Beans',
  'Lima Beans',
  'Corn',
  'Sweet Potatoes',
  'Cassava (Yuca)',
  'Taro',
  'Tomatoes',
  'Cucumbers',
  'Zucchini',
  'Eggplant',
  'Squash (Butternut, Acorn, Pumpkin)',
  'Bell Peppers (Red, Green, Yellow, Orange)',
  'Jalapeños',
  'Habaneros',
  'Serrano Peppers',
  'Poblano Peppers',
  'Mushrooms',
  'Button Mushrooms',
  'Cremini Mushrooms',
  'Portobello Mushrooms',
  'Shiitake Mushrooms',
  'Oyster Mushrooms',
  'Enoki Mushrooms',
  "Chicken",
  "Beef",
  "Fish",
  'Red Meat',
  'Beef (Steak, Ground Beef, Ribs, Brisket)',
  'Lamb (Chops, Ground Lamb, Leg of Lamb)',
  'Pork (Bacon, Ham, Sausage, Pork Chops)',
  'Veal (Cutlets, Ribs, Ground Veal)',
  'Goat Meat',
  'Chicken (Breast, Wings, Thighs, Drumsticks)',
  'Turkey (Whole, Breast, Ground Turkey)',
  'Duck (Breast, Legs, Whole Duck)',
  'Goose',
  'Quail',
  'Pheasant',
  'Seafood',
  'Fish (Salmon, Tuna, Cod, Haddock, Tilapia)',
  'Shellfish (Shrimp, Crab, Lobster, Clams, Mussels)',
  'Squid (Calamari)',
  'Octopus',
  'Scallops',
  'Processed Meats',
  'Hot Dogs',
  'Sausages (Bratwurst, Chorizo, Italian Sausage)',
  'Deli Meats (Ham, Turkey, Roast Beef, Salami, Pepperoni)',
  'Jerky (Beef, Turkey, Venison)',
  'Meatballs',
  'Venison (Deer)',
  'Bison',
  'Rabbit',
  'Wild Boar',
  'Kangaroo',
  // Add more or dynamically fetch from Hive/catalog if needed
];
