final List<Map<String, dynamic>> categories = [
  //1 Accessories
  {
    "name": "Accessories",
    "image": "assets/Images/Accessories.png",
    "products": [
      "Watches",
      "Bags",
      "Sunglasses",
      'Earrings',
      'Necklaces',
      'Bracelets',
      'Rings',
      'Anklets',
      'Toe Rings',
      'Nose Rings',
      'Cufflinks',
      'Brooches',
      'Pins',
      'Prescription Glasses',
      'Contact Lenses',
      'Blue-Light Glasses',
      'Hats',
      'Caps',
      'Beanies',
      'Berets',
      'Fedoras',
      'Visors',
      'Headbands',
      'Hijabs',
      'Turbans',
      'Hair Clips',
      'Hair Ties',
      'Shawls',
      'Silk Scarves',
      'Wool Scarves',
      'Bandanas',
      'Stoles',
      'Pashminas',
      'Gloves',
      'Mittens',
      'Fingerless Gloves',
      'Arm Warmers',
      'Tote Bags',
      'Clutches',
      'Crossbody Bags',
      'Shoulder Bags',
      'Backpacks',
      'Messenger Bags',
      'Leather Wallets',
      'Coin Purses',
      'RFID Wallets',
      'Money Clips',
      'Suitcases',
      'Passport Holders',
      'Travel Organizers',
      'Packing Cubes',
      'Duffel Bags',
      'Smartwatches',
      ' Fitness Bands',
      'VR Headsets',
      'Bluetooth Glasses',
      'Mobile Phone',
      'Phone Cases',
      'PopSockets',
      'Wireless Chargers',
      'Screen Protectors',
      'Styluses',
      'Laptop',
      'Laptop Sleeves',
      'Keyboard Covers',
      'Styluses',
      'Stands',
      'Cooling Pads',
      'Headphones',
      'Earbuds',
      'Wireless'
          'Speakers',
      'Microphones',
      'Diamond Rings',
      'Gold Chains',
      'Designer Watches',
      'Gucci',
      'Louis Vuitton',
      'Chanel',
      'Prada Bags',
      'Designer Sunglasses',
      'Perfumes',
      'Personalized Jewelry',
      'Kimono Belts (Obi)',
      'Hair Sticks',
      'Jade Bracelets',
      'Beaded Necklaces',
      'Head Wraps',
      'Maasai Bracelets',
      'Bindis',
      'Bangles',
      'Jhumkas (Indian Earrings)',
      'Abaya Belts',
      'Kufi Caps',
      'Keffiyeh Scarves',
      'Leather Keychains',
      'Personalized Keychains',
      'LED Keychains',
      'Folding Umbrellas',
      'Transparent Umbrellas',
      'Fancy Pens',
      ' Notebook Covers',
      'Bookmarks',
      'Car Air Fresheners',
      'Seat Covers',
      'Phone Holders',
      'Tents',
      'Sleeping Bags',
      'Flashlights',
      'Water Bottles Hydration Packs',
      'Desk Organizers & Stationery Holders',
      'Whiteboards & Corkboards',
      'Laptop Stands & Ergonomic Chairs',
      'Wall Clocks, Paintings, Picture Frames',
      'Vases & Indoor Plants',
      'Smart Plugs & Smart Bulbs',
      'Alexa',
      ' Google Nest',
      'Smart Assistants',
      'Decorative Lights & LED Strips',
      'Seat Covers & Steering Wheel Covers',
      'Phone Mounts & Car Chargers',
      'Dash Cams & Parking Sensors',
      'Roof Racks & Cargo Boxes',
      'Bike Racks & Hitch Mounts',
      'Motorcycle Helmets',
      'Gloves',
      ' Tank Bags',
      'Home Security Cameras & Sensors',
    ],
  },
  //2 Alcoholic Drinks
  {
    "name": "Alcoholic Drinks",
    "image": "assets/Images/Alcoholic Drinks.png",
    "products": [
      "Beer",
      "Whiskey",
      "Wine",
      'Lager (Pale Lager, Pilsner, Dark Lager, Vienna Lager)',
      'Ale (Pale Ale, India Pale Ale (IPA), Brown Ale, Scotch Ale)',
      'Stout (Irish Stout, Oatmeal Stout, Imperial Stout)',
      'Porter (Baltic Porter, American Porter)',
      'Wheat Beer (Hefeweizen, Witbier, Berliner Weisse)',
      'Sour Beer (Gose, Lambic, Flanders Red Ale)',
      'Pilsner',
      'Bock (Doppelbock, Eisbock)',
      'Cabernet Sauvignon',
      'Merlot',
      'Pinot Noir',
      'Syrah/Shiraz',
      'Malbec',
      'Zinfandel',
      'Sangiovese',
      'Tempranillo',
      'Chardonnay',
      'Sauvignon Blanc',
      'Pinot Grigio',
      'Riesling',
      'Moscato',
      'Viognier',
      'Chenin Blanc',
      'Provence Rosé',
      'White Zinfandel',
      'Grenache Rosé',
      'Champagne'
      'Prosecco'
      'Cava'
      'Moscato d\'Asti',
      'Port',
      'Sherry',
      'Madeira',
      'Vermouth',
      'Scotch Whisky (Single Malt, Blended)',
      'Bourbon',
      'Rye Whiskey',
      'Irish Whiskey',
      'Japanese Whisky',
      'Canadian Whisky',
      'Tennessee Whiskey',
      'Cognac',
      'Armagnac',
      'Calvados',
      'Pisco',
      'Light Rum (White Rum)',
      'Dark Rum (Black Rum)',
      'Spiced Rum',
      'Overproof Rum',
      'Gin',
      'London Dry Gin',
      'Old Tom Gin',
      'Plymouth Gin',
      'Genever',
      'Vodka',
      'Plain Vodka',
      'Flavored Vodka',
      'Tequila & Mezcal',
      'Blanco (Silver)',
      'Reposado (Aged)',
      'Añejo (Extra Aged)',
      'Mezcal',
      'Martini',
      'Margarita',
      'Mojito',
      'Old Fashioned',
      'Manhattan',
      'Negroni',
      'Daiquiri',
      'Whiskey Sour',
      'Cosmopolitan',
      'Pina Colada',
      'Bloody Mary',
      'Moscow Mule',
      'Mai Tai',
      'Zombie',
      'Painkiller',
      'Blue Hawaiian',
      'Frozen Margarita',
      'Frozen Daiquiri',
      'Irish Coffee',
      'Hot Toddy',
      'Mulled Wine',

        
    ],
  },
  //3 Baby Goods
  {
    "name": "Baby Goods",
    "image": "assets/Images/Baby Goods.png",
    "products": [
      "Diapers", 
      "Baby Food",
      "Toys",
      'Baby Clothing', 
      'Onesies (Bodysuits)',
      'Rompers',
      'Sleepsuits (Footed Pajamas)',
      'Baby Dresses',
      'Baby T-shirts & Tops',
      'Baby Pants & Leggings',
      'Baby Shorts',
      'Baby Socks & Booties',
      'Baby Hats & Beanies',
      'Baby Mittens',
      'Baby Jackets & Coats',
      'Baby Sweaters & Hoodies',
      'Baby Feeding Essentials ',
     ' Baby Bottles',
      'Bottle Nipples',
      'Sippy Cups',
      'Breast Pumps',
      'Formula Milk',
      'Baby Food & Purees',
      'Baby Food Makers',
      'High Chairs',
      'Bibs',
      'Burp Cloths',
      'Baby Utensils (Spoons, Forks)',
      'Baby Bowls & Plates',
      'Bottle Sterilizers',
      'Bottle Warmers',
      'Baby Diapering & Hygiene',
      'Disposable Diapers',
      'Cloth Diapers',
      'Diaper Rash Cream',
      'Baby Wipes',
      'Baby Powder',
      'Baby Lotion',
      'Baby Shampoo & Conditioner',
      'Baby Body Wash & Soap',
      'Baby Toothbrush & Toothpaste',
     ' Baby Nail Clippers',
      'Baby Hairbrush & Comb',
      'Changing Mats',
      'Baby Gear & Travel',
      'Strollers',
      'Car Seats',
      'Baby Carriers (Wraps, Slings)',
      'Baby Swings',
      'Baby Bouncers',
      'Baby Playpens',
      'Baby Walker',
      'Diaper Bags',
      'Pacifiers & Teethers',
      'Baby Monitors',
      'Baby Nursery & Bedding',
      'Cribs & Bassinets',
      'Crib Mattresses',
      'Baby Blankets',
      'Baby Pillows',
      'Sleep Sacks',
      'Mobiles & Nightlights',
      'Changing Tables',
      'Baby Toys & Entertainment',
      'Rattles & Teething Toys',
      'Plush Toys & Stuffed Animals',
      'Musical Toys',
      'Activity Gyms & Playmats',
      'Building Blocks',
      'Bath Toys',
      'Sensory Toys',
      ],
  },
  //4 Beverages (non-alcoholic)
  {
    "name": "Beverages (non-alcoholic)",
    "image": "assets/Images/Beverages.png",
    "products": [
      "Coca-Cola",
      "Juice",
      "Mineral Water",
      'Water & Mineral Water', 
      'Still Water',
      'Sparkling Water',
      'Flavored Water',
      'Alkaline Water',
      'Distilled Water',
      'Spring Water',
      'Electrolyte-Infused Water',
      'Soft Drinks & Carbonated Beverages',
      'Cola (Coke, Pepsi, etc.)',
      'Lemon-Lime Soda (Sprite, 7UP)',
      'Root Beer',
      'Ginger Ale',
      'Tonic Water',
      'Cream Soda',
      'Energy Drinks (Red Bull, Monster, etc.)',
      'Sports Drinks (Gatorade, Powerade, etc.)',
      'Juices & Fruit Drinks',
      'Orange Juice',
      'Apple Juice',
      'Grape Juice',
      'Pineapple Juice',
      'Cranberry Juice',
      'Pomegranate Juice',
      'Mango Juice',
      'Lemonade',
      'Limeade',
      'Watermelon Juice',
      'Mixed Berry Juice',
      'Carrot Juice',
      'Tomato Juice',
      'Dairy & Plant-Based Drinks',
      'Cow’s Milk (Whole, Skim, Low-Fat)',
      'Flavored Milk (Chocolate, Strawberry, etc.)',
      'Buttermilk',
      'Lassi',
      'Yogurt Drinks (Kefir, Ayran)',
      'Almond Milk',
      'Soy Milk',
      'Oat Milk',
      'Coconut Milk',
      'Cashew Milk',
      'Rice Milk',
      'Tea & Infusions',
      'Black Tea',
      'Green Tea',
      'White Tea',
      'Oolong Tea',
      'Herbal Tea (Chamomile, Peppermint, Hibiscus, etc.)',
      'Chai Tea',
      'Iced Tea',
      'Bubble Tea (Boba)',
      'Matcha Tea',
      'Coffee & Caffeinated Drinks',
      'Espresso',
      'Americano',
      'Cappuccino',
      'Latte',
      'Mocha',
      'Cold Brew Coffee',
      'Nitro Coffee',
      'Instant Coffee',
      'Decaffeinated Coffee',
      'Smoothies & Shakes',
      'Fruit Smoothies',
      'Green Smoothies',
      'Protein Shakes',
      'Milkshakes (Chocolate, Vanilla, Strawberry, etc.)',
      'raditional & Cultural Beverages',
      'Coconut Water',
      'Horchata (Rice & Cinnamon Drink)',
      'Falooda',
      'Aam Panna (Mango Drink)',
      'Sugarcane Juice',
      'Tamarind Juice',
      'Bael Juice',
      'Jallab (Middle Eastern Date Drink)',
      'Kvass (Fermented Rye Bread Drink)', 
       ],
  },
  //5 Bakery
  {
    "name": "Bakery",
    "image": "assets/Images/Bakery.png",
    "products": [
      "Bread",
      "Croissant",
      "Cake",
      'Breads', 
      'White Bread',
      'Whole Wheat Bread',
      'Multigrain Bread',
      'Sourdough Bread',
      'Rye Bread',
      'Baguette',
      'Ciabatta',
      'Brioche',
      'Pita Bread',
      'Focaccia',
      'Flatbread',
      'Naan',
      'Cornbread',
      'Gluten-Free Bread',
      'Rolls & Buns',
      'Dinner Rolls',
      'Hamburger Buns',
      'Hot Dog Buns',
      'Kaiser Rolls',
      'Ciabatta Rolls',
      'Pretzel Rolls',
      'Brioche Buns',
      'Cakes & Pastries',
      'Birthday Cakes',
      'Cheesecake',
      'Red Velvet Cake',
      'Chocolate Cake',
      'Pound Cake',
      'Carrot Cake',
      'Fruitcake',
      'Swiss Roll',
      'Angel Food Cake',
      'Black Forest Cake',
      'Tiramisu',
      'Opera Cake',
      'Ice Cream Cake',
      'Cookies & Biscuits',
      'Chocolate Chip Cookies',
      'Oatmeal Raisin Cookies',
      'Peanut Butter Cookies',
      'Sugar Cookies',
      'Shortbread',
      'Macarons',
      'Gingerbread Cookies',
      'Fortune Cookies',
      'Muffins & Cupcakes',
      'Blueberry Muffins',
      'Chocolate Muffins',
      'Banana Muffins',
      'Corn Muffins',
      'Red Velvet Cupcakes',
      'Vanilla Cupcakes',
      'Chocolate Cupcakes',
      'Croissants & Danish Pastries',
      'Butter Croissant',
      'Chocolate Croissant',
      'Almond Croissant',
      'Cheese Danish',
      'Fruit Danish',
      'Cinnamon Rolls',
      'Pies & Tarts',
      'Apple Pie',
      'Pumpkin Pie',
      'Pecan Pie',
      'Cherry Pie',
      'Lemon Meringue Pie',
      'Key Lime Pie',
      'Custard Tart',
      'Fruit Tart',
      'Doughnuts & Fritters',
      'Glazed Doughnuts',
      'Chocolate Doughnuts',
      'Jelly-Filled Doughnuts',
      'Cream-Filled Doughnuts',
      'Apple Fritters',
      'Churros',
      'Savory Baked Goods',
      'Garlic Bread',
      'Pretzels',
      'Bagels',
      'Empanadas',
      'Samosas',
      'Quiche',
      'Puff Pastry Snacks',  
      ],
  },
  //6 Canned Goods
  {
    "name": "Canned Goods",
    "image": "assets/Images/Canned Goods.png",
    "products": [
      "Tuna", 
      "Corn", 
      "Beans",
      'Canned Vegetables',
      'Canned Corn',
      'Canned Peas',
      'Canned Green Beans',
      'Canned Carrots',
      'Canned Mushrooms',
      'Canned Spinach',
      'Canned Asparagus',
      'Canned Tomatoes',
      'Canned Beets',
      'Canned Potatoes',
      'Canned Mixed Vegetables',
      'Canned Fruits',
      'Canned Peaches',
      'Canned Pineapple',
      'Canned Pears',
      'Canned Mandarin Oranges',
      'Canned Applesauce',
      'Canned Cherries',
      'Canned Mango',
      'Canned Apricots',
      'Canned Lychee',
      'Canned Fruit Cocktail',
      'Canned Beans & Legumes', 
      'Canned Black Beans',
      'Canned Kidney Beans',
      'Canned Chickpeas (Garbanzo Beans)',
      'Canned Pinto Beans',
      'Canned White Beans (Cannellini)',
      'Canned Lentils',
      'Canned Refried Beans',
      'Canned Baked Beans',
      'Canned Meat & Seafood',
      'Canned Tuna',
      'Canned Salmon',
      'Canned Sardines',
      'Canned Anchovies',
      'Canned Crab Meat',
      'Canned Chicken',
      'Canned Turkey',
      'Canned Corned Beef',
      'Canned Ham',
      'Canned Spam',
      'Canned Soups & Broths',
      'Canned Tomato Soup',
      'Canned Chicken Noodle Soup',
      'Canned Vegetable Soup',
      'Canned Clam Chowder',
      'Canned Minestrone',
      'Canned Beef Stew',
      'Canned Chili',
      'Canned French Onion Soup',
      'Canned Mushroom Soup',
      'Canned Lentil Soup',
      'Canned Chicken Broth',
      'Canned Beef Broth',
      'Canned Vegetable Broth',
      'Canned Pasta & Meals', 
      'Canned SpaghettiOs',
      'Canned Ravioli',
      'Canned Mac & Cheese',
      'Canned Lasagna',
      'Canned Chili Mac',
      'Canned Beefaroni',
      'Canned Sauces & Condiments',
      'Canned Tomato Sauce',
      'Canned Pasta Sauce',
      'Canned Salsa',
      'Canned Enchilada Sauce',
      'Canned Coconut Milk',
      'Canned Alfredo Sauce',
      'Canned Pesto',
      'Canned Dairy & Desserts',
      'Canned Condensed Milk',
      'Canned Evaporated Milk',
      'Canned Whipped Cream',
      'Canned Rice Pudding',
      'Canned Custard',
      'Canned Chocolate Syrup',
           ],
  },
  {
    "name": "Cleaners",
    "image": "assets/Images/Cleaner.png",
    "products": ["Detergent", "Bleach", "Soap"],
  },
  {
    "name": "Clothes & Shoes",
    "image": "assets/Images/Clothes&Shoes.png",
    "products": ["T-Shirt", "Jeans", "Sneakers"],
  },
  {
    "name": "Coffee, Tea & Cocoa",
    "image": "assets/Images/Coffee, Tea&Cocoa.png",
    "products": ["Coffee Beans", "Green Tea", "Hot Chocolate"],
  },
  {
    "name": "Dairy",
    "image": "assets/Images/Dairy.png",
    "products": ["Milk", "Cheese", "Butter"],
  },
  {
    "name": "Dry Goods",
    "image": "assets/Images/Dry Goods.png",
    "products": ["Rice", "Pasta", "Lentils"],
  },
  {
    "name": "Flowers",
    "image": "assets/Images/Flower.png",
    "products": ["Jasmin", "Rose", "Cornflower"],
  },
  {
    "name": "Frozen Foods",
    "image": "assets/Images/Frozen Foods.png",
    "products": ["Frozen Meat", "Ice cream", "Ice cubes"],
  },
  {
    "name": "Fruits",
    "image": "assets/Images/Fruits.png",
    "products": ["Apple", "Mango", "Orange"],
  },
  {
    "name": "Meat",
    "image": "assets/Images/Meat.png",
    "products": ["Chicken", "Beef", "Fish"],
  },
];
